- name: set up docker secret command
  set_fact:
    docker_secret_cmd: "docker secret"

- name: add secret driver option if applicable
  set_fact:
    docker_secret_cmd: "{{ docker_secret_cmd }} -d {{ minio_secret_driver }}"
  when:
    - minio_secret_driver | bool

- name: "check to see if {{ item.name }} secret exists"
  shell: "{{ docker_secret_cmd }} inspect {{ item.name }}"
  ignore_errors: true
  register: secret_exists

- name: "store {{ item.name }} to docker swarm secret store"
  shell: "echo '{{ item.secret }}' | {{ docker_secret_cmd }} create {{ item.name }} -"
  when: secret_exists.rc != 0
